default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

production:
  <<: *default
  database: omniauthapp_production
  host: localhost
  username: root
  password: password


development:
  <<: *default
  database: omniauthapp
  host: localhost
  username: root
  password: password

test:
  <<: *default
  database: omniauthapp_test
  host: localhost
  username: root
  password: password

staging:
  <<: *default
  database: omniauthapp_staging
  host: localhost
  username: root
  password: password