# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85c240db77b6fedc8e45a0e56a17b5d10837cf456a71fa091431d808db3f5f49616df001af7639da7c5eb6a67176de21ecf286f20487b3bbc1332a12ef4dea3c
  google_application_id: sdsgdsgsgs
  google_secret_id: sdfdsgs
  twitter_secret_id:
    app_host: 'localhost'
    sender_email: 'sndp5678@gmail.com'
    sender_password: 'sandeep12'

test:
  secret_key_base: 0044f977ed8080e4db2644692acf03e226091655ad8a1099d36694e20b37861917bb5f16a9541a37c4dcdc1a4de9626218d5c7164a65fa6308fc2cc63dbfd834

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_application_id: <%= ENV["google_application_id"] %>
  google_secret_id: <%= ENV["google_secret_id"] %>

